version: '3'

services:
  backand:
    build: ./
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge